#FROM node:6.11.0-alpine
FROM node:4.8.2-alpine

# Oddly, node-sass requires both python and make to build bindings
RUN apk add python make g++
# Install gulp globally so it can be used during builds
RUN npm install --global gulp-cli
